name: Go Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SRC_DIR: ./mqtt-daytime-notifier
    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ${SRC_DIR}

      - name: Build x86 binary
        run: GOOS=linux GOARCH=amd64 go build -o mqtt_publisher_x86 ${SRC_DIR}

      - name: Build arm64 binary
        run: GOOS=linux GOARCH=arm64 go build -o mqtt_publisher_arm64 ${SRC_DIR}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PAT }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.PAT }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            ./mqtt_publisher_x86
            ./mqtt_publisher_arm64
